server:
  port: 8881
spring:
  name: gateway
  cloud:
    gateway:
      routes:
        - id: back-service
          uri: http://patientService:8081/  # L'URL du microservice Back patient
          filters:
            - HmacValidationFilter
            - AddRequestHeader=Gateway-Secret, my-secret-key
          predicates:
            - Path=/patient/**            # Si l'URL de la requête commence par /patient, alors acheminer la requête vers le micro service patient
        - id: notes-service
          uri: http://notesService:8082/  # L'URL du microservice Back notes
          filters:
            - HmacValidationFilter
            - AddRequestHeader=Gateway-Secret, my-secret-key
          predicates:
            - Path=/notes/**               # Si l'URL de la requête commence par /notes, alors acheminer la requête vers le micro service notes
